-- Backfill Python-derived QC rule cells so processing output is explicit
-- instead of SQL NULL. Reviewer workflow columns intentionally remain nullable.

ALTER TABLE qc_rule_result
    ADD COLUMN IF NOT EXISTS target_field VARCHAR(255),
    ADD COLUMN IF NOT EXISTS pdf_page INTEGER,
    ADD COLUMN IF NOT EXISTS bbox_x REAL,
    ADD COLUMN IF NOT EXISTS bbox_y REAL,
    ADD COLUMN IF NOT EXISTS bbox_w REAL,
    ADD COLUMN IF NOT EXISTS bbox_h REAL;

ALTER TABLE qc_rule_result_aud
    ADD COLUMN IF NOT EXISTS message TEXT,
    ADD COLUMN IF NOT EXISTS details TEXT,
    ADD COLUMN IF NOT EXISTS action_item TEXT,
    ADD COLUMN IF NOT EXISTS appraisal_value TEXT,
    ADD COLUMN IF NOT EXISTS engagement_value TEXT,
    ADD COLUMN IF NOT EXISTS severity VARCHAR(20),
    ADD COLUMN IF NOT EXISTS target_field VARCHAR(255),
    ADD COLUMN IF NOT EXISTS pdf_page INTEGER,
    ADD COLUMN IF NOT EXISTS bbox_x REAL,
    ADD COLUMN IF NOT EXISTS bbox_y REAL,
    ADD COLUMN IF NOT EXISTS bbox_w REAL,
    ADD COLUMN IF NOT EXISTS bbox_h REAL;

UPDATE qc_rule_result SET
    rule_name = COALESCE(rule_name, rule_id, 'UNKNOWN_RULE'),
    message = COALESCE(message, 'No rule message provided.'),
    details = COALESCE(details, '{}'),
    action_item = COALESCE(action_item, verify_question, rejection_text, 'No reviewer action required.'),
    appraisal_value = COALESCE(appraisal_value, '__NO_APPRAISAL_VALUE__'),
    engagement_value = COALESCE(engagement_value, '__NO_ENGAGEMENT_VALUE__'),
    confidence_score = COALESCE(confidence_score, 0.0),
    extracted_value = COALESCE(extracted_value, '__NO_EXTRACTED_VALUE__'),
    expected_value = COALESCE(expected_value, '__NO_EXPECTED_VALUE__'),
    verify_question = COALESCE(verify_question, ''),
    rejection_text = COALESCE(rejection_text, ''),
    evidence = COALESCE(evidence, '[]'),
    review_required = COALESCE(review_required, false),
    severity = COALESCE(severity, 'STANDARD'),
    target_field = COALESCE(target_field, 'checklist_rule'),
    pdf_page = COALESCE(pdf_page, 0),
    bbox_x = COALESCE(bbox_x, 0.0),
    bbox_y = COALESCE(bbox_y, 0.0),
    bbox_w = COALESCE(bbox_w, 0.0),
    bbox_h = COALESCE(bbox_h, 0.0);

UPDATE qc_rule_result_aud SET
    rule_name = COALESCE(rule_name, rule_id, 'UNKNOWN_RULE'),
    message = COALESCE(message, 'No rule message provided.'),
    details = COALESCE(details, '{}'),
    action_item = COALESCE(action_item, verify_question, rejection_text, 'No reviewer action required.'),
    appraisal_value = COALESCE(appraisal_value, '__NO_APPRAISAL_VALUE__'),
    engagement_value = COALESCE(engagement_value, '__NO_ENGAGEMENT_VALUE__'),
    confidence_score = COALESCE(confidence_score, 0.0),
    extracted_value = COALESCE(extracted_value, '__NO_EXTRACTED_VALUE__'),
    expected_value = COALESCE(expected_value, '__NO_EXPECTED_VALUE__'),
    verify_question = COALESCE(verify_question, ''),
    rejection_text = COALESCE(rejection_text, ''),
    evidence = COALESCE(evidence, '[]'),
    review_required = COALESCE(review_required, false),
    severity = COALESCE(severity, 'STANDARD'),
    target_field = COALESCE(target_field, 'checklist_rule'),
    pdf_page = COALESCE(pdf_page, 0),
    bbox_x = COALESCE(bbox_x, 0.0),
    bbox_y = COALESCE(bbox_y, 0.0),
    bbox_w = COALESCE(bbox_w, 0.0),
    bbox_h = COALESCE(bbox_h, 0.0);

ALTER TABLE qc_rule_result
    ALTER COLUMN rule_name SET DEFAULT 'UNKNOWN_RULE',
    ALTER COLUMN message SET DEFAULT 'No rule message provided.',
    ALTER COLUMN details SET DEFAULT '{}',
    ALTER COLUMN action_item SET DEFAULT 'No reviewer action required.',
    ALTER COLUMN appraisal_value SET DEFAULT '__NO_APPRAISAL_VALUE__',
    ALTER COLUMN engagement_value SET DEFAULT '__NO_ENGAGEMENT_VALUE__',
    ALTER COLUMN confidence_score SET DEFAULT 0.0,
    ALTER COLUMN extracted_value SET DEFAULT '__NO_EXTRACTED_VALUE__',
    ALTER COLUMN expected_value SET DEFAULT '__NO_EXPECTED_VALUE__',
    ALTER COLUMN verify_question SET DEFAULT '',
    ALTER COLUMN rejection_text SET DEFAULT '',
    ALTER COLUMN evidence SET DEFAULT '[]',
    ALTER COLUMN review_required SET DEFAULT false,
    ALTER COLUMN severity SET DEFAULT 'STANDARD',
    ALTER COLUMN target_field SET DEFAULT 'checklist_rule',
    ALTER COLUMN pdf_page SET DEFAULT 0,
    ALTER COLUMN bbox_x SET DEFAULT 0.0,
    ALTER COLUMN bbox_y SET DEFAULT 0.0,
    ALTER COLUMN bbox_w SET DEFAULT 0.0,
    ALTER COLUMN bbox_h SET DEFAULT 0.0;

ALTER TABLE qc_rule_result
    ALTER COLUMN rule_name SET NOT NULL,
    ALTER COLUMN message SET NOT NULL,
    ALTER COLUMN details SET NOT NULL,
    ALTER COLUMN action_item SET NOT NULL,
    ALTER COLUMN appraisal_value SET NOT NULL,
    ALTER COLUMN engagement_value SET NOT NULL,
    ALTER COLUMN confidence_score SET NOT NULL,
    ALTER COLUMN extracted_value SET NOT NULL,
    ALTER COLUMN expected_value SET NOT NULL,
    ALTER COLUMN verify_question SET NOT NULL,
    ALTER COLUMN rejection_text SET NOT NULL,
    ALTER COLUMN evidence SET NOT NULL,
    ALTER COLUMN review_required SET NOT NULL,
    ALTER COLUMN severity SET NOT NULL,
    ALTER COLUMN target_field SET NOT NULL,
    ALTER COLUMN pdf_page SET NOT NULL,
    ALTER COLUMN bbox_x SET NOT NULL,
    ALTER COLUMN bbox_y SET NOT NULL,
    ALTER COLUMN bbox_w SET NOT NULL,
    ALTER COLUMN bbox_h SET NOT NULL;
