"""phase2_field_meta

Revision ID: 4c5d9f3a1583
Revises: f27250e89c7c
Create Date: 2026-04-25 15:22:07.229515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c5d9f3a1583'
down_revision: Union[str, Sequence[str], None] = 'f27250e89c7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extracted_fields', sa.Column('raw_ocr_text', sa.Text(), nullable=True))
    op.add_column('extracted_fields', sa.Column('correction_applied', sa.Boolean(), nullable=True))
    op.alter_column('extracted_fields', 'extraction_method',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('extracted_fields', 'extraction_method',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('extracted_fields', 'correction_applied')
    op.drop_column('extracted_fields', 'raw_ocr_text')
    # ### end Alembic commands ###
