"""phase3_rules_config_llm_cache

Revision ID: c13dab69bd6c
Revises: 4c5d9f3a1583
Create Date: 2026-04-25 15:49:42.168712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c13dab69bd6c'
down_revision: Union[str, Sequence[str], None] = '4c5d9f3a1583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_response_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('task', sa.String(length=50), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_response_cache_input_hash'), 'llm_response_cache', ['input_hash'], unique=True)
    op.create_table('rules_config',
    sa.Column('rule_id', sa.String(length=20), nullable=False),
    sa.Column('rule_name', sa.String(length=200), nullable=False),
    sa.Column('rule_category', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('severity_level', sa.String(length=20), nullable=True),
    sa.Column('applicable_loan_types', sa.String(length=200), nullable=True),
    sa.Column('execution_order', sa.Integer(), nullable=True),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_index('ix_rules_config_active', 'rules_config', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rules_config_active', table_name='rules_config')
    op.drop_table('rules_config')
    op.drop_index(op.f('ix_llm_response_cache_input_hash'), table_name='llm_response_cache')
    op.drop_table('llm_response_cache')
    # ### end Alembic commands ###
