"""initial_tables

Revision ID: f27250e89c7c
Revises: 
Create Date: 2026-04-25 14:44:19.962059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f27250e89c7c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('upload_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=True)
    op.create_table('extracted_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_value', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('extraction_method', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_extracted_doc_field', 'extracted_fields', ['document_id', 'field_name'], unique=False)
    op.create_table('feedback_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.String(length=20), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('original_status', sa.String(length=20), nullable=True),
    sa.Column('corrected_status', sa.String(length=20), nullable=True),
    sa.Column('original_value', sa.Text(), nullable=True),
    sa.Column('corrected_value', sa.Text(), nullable=True),
    sa.Column('operator_comment', sa.Text(), nullable=True),
    sa.Column('feedback_timestamp', sa.DateTime(), nullable=True),
    sa.Column('used_for_training', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_doc', 'feedback_events', ['document_id'], unique=False)
    op.create_index('ix_feedback_not_trained', 'feedback_events', ['used_for_training'], unique=False)
    op.create_table('page_ocr_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('extraction_method', sa.String(length=20), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('has_tables', sa.Boolean(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash', 'page_number', name='uq_page_ocr_hash_page')
    )
    op.create_index('ix_page_ocr_file_hash', 'page_ocr_results', ['file_hash'], unique=False)
    op.create_index(op.f('ix_page_ocr_results_file_hash'), 'page_ocr_results', ['file_hash'], unique=False)
    op.create_table('rule_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.String(length=20), nullable=False),
    sa.Column('rule_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('action_item', sa.Text(), nullable=True),
    sa.Column('appraisal_value', sa.Text(), nullable=True),
    sa.Column('engagement_value', sa.Text(), nullable=True),
    sa.Column('review_required', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rule_results_doc_rule', 'rule_results', ['document_id', 'rule_id'], unique=False)
    op.create_index('ix_rule_results_status', 'rule_results', ['status'], unique=False)
    op.create_table('training_examples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feature_type', sa.String(length=50), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('source_feedback_id', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_feedback_id'], ['feedback_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_training_feature_type', 'training_examples', ['feature_type'], unique=False)
    op.create_index('ix_training_label', 'training_examples', ['label'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_training_label', table_name='training_examples')
    op.drop_index('ix_training_feature_type', table_name='training_examples')
    op.drop_table('training_examples')
    op.drop_index('ix_rule_results_status', table_name='rule_results')
    op.drop_index('ix_rule_results_doc_rule', table_name='rule_results')
    op.drop_table('rule_results')
    op.drop_index(op.f('ix_page_ocr_results_file_hash'), table_name='page_ocr_results')
    op.drop_index('ix_page_ocr_file_hash', table_name='page_ocr_results')
    op.drop_table('page_ocr_results')
    op.drop_index('ix_feedback_not_trained', table_name='feedback_events')
    op.drop_index('ix_feedback_doc', table_name='feedback_events')
    op.drop_table('feedback_events')
    op.drop_index('ix_extracted_doc_field', table_name='extracted_fields')
    op.drop_table('extracted_fields')
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
