import fs from "node:fs/promises";
import path from "node:path";
import type { ScenarioStore } from "../state/store";
import type { LoadTestResult } from "../scenarios/load-test";

export async function writeScenarioReport(store: ScenarioStore, name: string): Promise<string> {
  const dir = path.resolve("reports");
  await fs.mkdir(dir, { recursive: true });
  const file = path.join(dir, `${name}-${new Date().toISOString().replace(/[:.]/g, "-")}.json`);
  await fs.writeFile(
    file,
    JSON.stringify(
      {
        name,
        batch: store.batch,
        activeQcResultId: store.activeQcResultId,
        events: store.events
      },
      null,
      2
    )
  );
  return file;
}

export async function writeLoadTestReport(result: LoadTestResult): Promise<string> {
  const dir = path.resolve("reports");
  await fs.mkdir(dir, { recursive: true });
  const ts = new Date().toISOString().replace(/[:.]/g, "-");

  // ── Metrics ────────────────────────────────────────────────────────────────
  const completed = result.workers.filter(w => w.status === "completed");
  const failed = result.workers.filter(w => w.status === "failed");
  const durations = completed.map(w => w.durationMs);
  const avg = durations.length > 0 ? Math.round(durations.reduce((a, b) => a + b, 0) / durations.length) : 0;
  const max = durations.length > 0 ? Math.max(...durations) : 0;
  const min = durations.length > 0 ? Math.min(...durations) : 0;

  const perWorker = result.workers.map(w => {
    const events = w.store.events;
    const decisions = events.filter(e => e.event === "decision:saved").length;
    const qcStarted = events.find(e => e.event === "qc:started")?.at;
    const qcDone = events.find(e => e.event === "qc:skipped" || e.event === "qc:started")?.at;
    const reviewSubmitted = events.find(e => e.event === "review:submitted")?.at;
    return {
      worker: `${w.adminLabel}+${w.reviewerLabel}`,
      batchId: w.batchId,
      status: w.status,
      durationMs: w.durationMs,
      durationSec: parseFloat((w.durationMs / 1000).toFixed(2)),
      decisions,
      error: w.error,
      timestamps: { qcStarted, qcDone, reviewSubmitted }
    };
  });

  // ── JSON report ────────────────────────────────────────────────────────────
  const jsonFile = path.join(dir, `load-test-${ts}.json`);
  await fs.writeFile(jsonFile, JSON.stringify({
    meta: {
      startedAt: result.startedAt,
      finishedAt: result.finishedAt,
      totalDurationMs: result.totalDurationMs,
      totalDurationSec: parseFloat((result.totalDurationMs / 1000).toFixed(2))
    },
    summary: {
      totalWorkers: result.workers.length,
      completed: completed.length,
      failed: failed.length,
      successRate: `${Math.round((completed.length / result.workers.length) * 100)}%`,
      avgWorkerSec: parseFloat((avg / 1000).toFixed(2)),
      minWorkerSec: parseFloat((min / 1000).toFixed(2)),
      maxWorkerSec: parseFloat((max / 1000).toFixed(2)),
    },
    workers: perWorker,
    allEvents: result.workers.flatMap(w =>
      w.store.events.map(e => ({ worker: w.adminLabel, ...e }))
    ).sort((a, b) => a.at.localeCompare(b.at))
  }, null, 2));

  // ── Markdown summary ───────────────────────────────────────────────────────
  const mdFile = path.join(dir, `load-test-${ts}-summary.md`);
  const lines = [
    `# Load Test Report`,
    ``,
    `**Started:** ${result.startedAt}  `,
    `**Finished:** ${result.finishedAt}  `,
    `**Total wall time:** ${(result.totalDurationMs / 1000).toFixed(1)}s`,
    ``,
    `## Performance Summary`,
    ``,
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Concurrent users | ${result.workers.length * 2} (${result.workers.length} admin + ${result.workers.length} reviewer) |`,
    `| Workers completed | ${completed.length} / ${result.workers.length} |`,
    `| Success rate | ${Math.round((completed.length / result.workers.length) * 100)}% |`,
    `| Total duration | ${(result.totalDurationMs / 1000).toFixed(1)}s |`,
    `| Avg worker duration | ${(avg / 1000).toFixed(1)}s |`,
    `| Min worker duration | ${(min / 1000).toFixed(1)}s |`,
    `| Max worker duration | ${(max / 1000).toFixed(1)}s |`,
    ``,
    `## Per-Worker Results`,
    ``,
    `| Worker | Batch | Status | Duration | Decisions |`,
    `|--------|-------|--------|----------|-----------|`,
    ...perWorker.map(w =>
      `| ${w.worker} | ${w.batchId} | ${w.status === "completed" ? "✅" : "❌"} ${w.status} | ${w.durationSec}s | ${w.decisions} |`
    ),
    ``,
    ...(failed.length > 0 ? [
      `## Failures`,
      ``,
      ...failed.map(w => [
        `### ${w.adminLabel}+${w.reviewerLabel}`,
        `\`\`\``,
        w.error ?? "unknown error",
        `\`\`\``,
      ]).flat(),
      ``
    ] : []),
    `---`,
    `*Report generated by Ardur Multi-Agent Brain*`,
  ];
  await fs.writeFile(mdFile, lines.join("\n"));

  console.log(`[report] JSON  → ${jsonFile}`);
  console.log(`[report] MD    → ${mdFile}`);
  return jsonFile;
}
