#!/usr/bin/env bash
# Auto-generate the SHAL .env files for a local native setup (macOS + Ubuntu).
# Idempotent: only creates a file if it does NOT already exist — never overwrites,
# so secrets stay stable and your manual edits are preserved.
#
#   ./scripts/init-env.sh          # create any missing .env files
#   FORCE=1 ./scripts/init-env.sh  # recreate even if they exist (regenerates secrets!)
#
# Defaults match the documented local setup:
#   PostgreSQL  role=shal pass=shal db=shal_qc on localhost:5432
#   Redis       localhost:6379 (no password)
#   Admin       harshal@eaglexinfo.com / Admin123!
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# ── Generate a random hex secret (openssl → python → urandom fallback) ──
gen_secret() {  # nbytes
  local n="${1:-32}"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$n"
  elif command -v python3 >/dev/null 2>&1; then
    python3 -c "import secrets;print(secrets.token_hex($n))"
  else
    head -c "$n" /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

# ── Detect this machine's primary LAN IP (Linux + macOS) ───────────────
detect_lan_ip() {
  local ip=""
  if command -v hostname >/dev/null 2>&1 && hostname -I >/dev/null 2>&1; then
    ip="$(hostname -I 2>/dev/null | awk '{print $1}')"      # Linux
  fi
  if [[ -z "$ip" ]] && command -v ipconfig >/dev/null 2>&1; then
    ip="$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || true)"  # macOS
  fi
  echo "$ip"
}
LAN_IP="$(detect_lan_ip)"

# ── Write a file only if missing (or FORCE=1) ──────────────────────────
write_if_absent() {  # path  <<<content
  local path="$1"; shift
  if [[ -f "$path" && "${FORCE:-0}" != "1" ]]; then
    echo "[init-env] exists, keeping: ${path#$REPO_ROOT/}"
    return
  fi
  cat > "$path"
  echo "[init-env] wrote: ${path#$REPO_ROOT/}"
}

JWT_SECRET="$(gen_secret 32)"
INTERNAL_API_KEY="$(gen_secret 24)"

# ── Real secrets (e.g. GROQ key) come from an UNTRACKED local file or env ──
# scripts/.env.secrets is gitignored, so keys land in ocr-service/.env on every
# machine WITHOUT ever being committed to the public repo. See .env.secrets.example.
SECRETS_FILE="$REPO_ROOT/scripts/.env.secrets"
if [[ -f "$SECRETS_FILE" ]]; then
  set -a; # shellcheck disable=SC1090
  source "$SECRETS_FILE"; set +a
  echo "[init-env] loaded local secrets from scripts/.env.secrets"
fi
GROQ_API_KEY="${GROQ_API_KEY:-}"
GROQ_VISION_API_KEY="${GROQ_VISION_API_KEY:-$GROQ_API_KEY}"
if [[ -n "$GROQ_API_KEY" ]]; then
  echo "[init-env] GROQ key found — will be written into ocr-service/.env"
else
  echo "[init-env] no GROQ key (set one in scripts/.env.secrets to enable LLM extraction)"
fi

# ── 1. Root .env (Java Spring Boot + shared keys) ──────────────────────
write_if_absent "$REPO_ROOT/.env" <<EOF
# ============================================================
# SHAL — local dev environment (auto-generated by scripts/init-env.sh)
# Native services: PostgreSQL + Redis on localhost. Do NOT commit.
# ============================================================

# ── Database (local native PostgreSQL) ──────────────────────
DB_URL=jdbc:postgresql://localhost:5432/shal_qc
DB_USERNAME=shal
DB_PASSWORD=shal

# ── Java Spring Boot ────────────────────────────────────────
JWT_SECRET=$JWT_SECRET
ADMIN_EMAIL=harshal@eaglexinfo.com
ADMIN_PASSWORD=Admin123!
COOKIE_SECURE=false

# ── Shared Java/Python internal API key (must match across services) ──
INTERNAL_API_KEY=$INTERNAL_API_KEY

# ── OCR service location ────────────────────────────────────
OCR_SERVICE_URL=http://127.0.0.1:5001
OCR_TIMEOUT=900
OCR_RETRIES=2
STORAGE_PATH=./uploads

# ── Redis (local native, no password) ───────────────────────
REDIS_URL=redis://localhost:6379/0
REDIS_PASSWORD=

# ── Tomcat working dir (portable: /tmp exists on Linux + macOS) ──
TOMCAT_BASEDIR=/tmp/shal-tomcat
EOF

# ── 2. ocr-service/.env (Python service-specific) ──────────────────────
# INTERNAL_API_KEY is intentionally NOT duplicated here — start-ocr.sh /
# start-celery.sh source ../.env first, so both services share one key.
write_if_absent "$REPO_ROOT/ocr-service/.env" <<EOF
# ============================================================
# SHAL OCR service — local dev (auto-generated by scripts/init-env.sh)
# INTERNAL_API_KEY is loaded from ../.env (shared key — keep it only there).
# ============================================================

# Shared local PostgreSQL (psycopg2 driver) — Python-owned tables
DATABASE_URL=postgresql+psycopg2://shal:shal@localhost:5432/shal_qc

# Celery broker + result backend + Groq TPM token bucket
REDIS_URL=redis://127.0.0.1:6379/0

# "*" = allow any origin (localhost + LAN IP) for dev/network access.
# Lock this to a fixed list in production.
ALLOWED_ORIGINS=*

# Per-process SQLAlchemy pool (keep small so N Celery workers don't oversubscribe PG)
DB_POOL_SIZE=2
DB_MAX_OVERFLOW=3

ENVIRONMENT=development
LOG_LEVEL=INFO
MODEL_VERSION=adaptive-1.0.0

# ── Groq cloud LLM (structured-extraction brain) ────────────
# Key is injected from scripts/.env.secrets (untracked). Without it the service
# still runs (synchronous fallback + keyword extraction), with reduced grid accuracy.
GROQ_API_KEY=$GROQ_API_KEY
GROQ_MODEL=openai/gpt-oss-120b
GROQ_VISION_API_KEY=$GROQ_VISION_API_KEY
GROQ_VISION_MODEL=meta-llama/llama-4-scout-17b-16e-instruct
GROQ_TPM_LIMIT=6000

# ── Google Cloud Vision (comparable-photo QC) — off by default ──
VISION_ENABLED=false
GOOGLE_CLOUD_VISION_API_KEY=
GOOGLE_APPLICATION_CREDENTIALS=
VISION_MAX_PAGES=3
VISION_TIMEOUT=30
EOF

# ── 3. frontend/.env.local ─────────────────────────────────────────────
# NEXT_PUBLIC_JAVA_URL is intentionally NOT pinned: lib/config.ts auto-derives
# the backend URL from whatever host the browser loaded (localhost or LAN IP),
# so the app works both locally and over the network. ALLOWED_DEV_ORIGINS lets
# Next's HMR websocket load over the LAN IP.
write_if_absent "$REPO_ROOT/frontend/.env.local" <<EOF
# Backend URL is auto-derived from the browser host (see lib/config.ts).
# Uncomment ONLY to force a fixed backend host:
# NEXT_PUBLIC_JAVA_URL=http://localhost:8080

# Hosts allowed to load Next.js dev (HMR) resources cross-origin.
ALLOWED_DEV_ORIGINS=${LAN_IP}
EOF

# ── Migrate an existing .env.local from the old localhost-pinned default ──
LOCAL_ENV="$REPO_ROOT/frontend/.env.local"
if [[ -f "$LOCAL_ENV" ]]; then
  # Comment out the stale hard pin to localhost (broke LAN/IP access).
  if grep -q '^NEXT_PUBLIC_JAVA_URL=http://localhost:8080$' "$LOCAL_ENV"; then
    sed -i.bak 's|^NEXT_PUBLIC_JAVA_URL=http://localhost:8080$|# NEXT_PUBLIC_JAVA_URL auto-derived from browser host (was pinned to localhost)|' "$LOCAL_ENV"
    rm -f "$LOCAL_ENV.bak"
    echo "[init-env] migrated frontend/.env.local: backend URL now auto-derived"
  fi
  # Ensure ALLOWED_DEV_ORIGINS is present (append the detected LAN IP if missing).
  if [[ -n "$LAN_IP" ]] && ! grep -q '^ALLOWED_DEV_ORIGINS=' "$LOCAL_ENV"; then
    printf '\n# Hosts allowed to load Next.js dev (HMR) resources cross-origin.\nALLOWED_DEV_ORIGINS=%s\n' "$LAN_IP" >> "$LOCAL_ENV"
    echo "[init-env] added ALLOWED_DEV_ORIGINS=$LAN_IP to frontend/.env.local"
  fi
fi

[[ -n "$LAN_IP" ]] && echo "[init-env] LAN IP detected: $LAN_IP (app reachable at http://$LAN_IP:3000)"
echo "[init-env] Done. Edit ocr-service/.env to add GROQ_API_KEY for full LLM extraction."
